### ISSUE TITLE
Table "mttest"."etsensor" not reachable or non existing

### ISSUE THREAD

**Issue by HervePruvost** [N5GEH/n5geh.platform#4]
Hi,
Following the steps in Grafana for connecting to the DB and making the query, it appears the table given in the example doesn't exist:

![mttest-table-issue](https://user-images.githubusercontent.com/24978853/189166612-85308f9f-354a-4d36-8382-1ea68bc38b6d.JPG)

Any idea what is going wrong?

**Comment by StWiemann** [comment]
You can inspect the DB under localhost:4200. It seems like the table wasn't created yet.

**Comment by HervePruvost** [comment]
Does it mean one have first to create the table manually inside the crateDB? Or should you correct this inside the source code of the crate docker image?

**Comment by djs0109** [comment]
Hi, you don't need to create a table by yourself. I think the problem is, that you did not create a QuantumLeap subscription inside the context broker. In this [tutorial ](https://fiware-tutorials.readthedocs.io/en/latest/time-series-data.html), you will learn why it is necessary and how to do it right.
