### ISSUE TITLE
missing database/table in crate

### ISSUE THREAD

**Issue by HervePruvost** [N5GEH/n5geh.platform#6]
It looks the issue was not completely solved:

        Does it mean one have first to create the table manually inside the crateDB? Or should you correct this inside the source code of the crate docker image?

_Originally posted by @HervePruvost in https://github.com/N5GEH/n5geh.platform/issues/4#issuecomment-1342660513_

**Comment by SBlechmann** [comment]
Hey Hervé,
as discussed 2 weeks ago - and sorry for the late reply:

You need to create a subscription in Orion with your QuantumLeap as notification endpoint. Once this subscriptions fires, QuantumLeap will create the according tables in crate automatically.
For further information, please, see [this tutorial](https://fiware-tutorials.readthedocs.io/en/latest/time-series-data.html).

Hope this helps, otherwise you can come back to me.

Cheers,
Sebastian
